### ISSUE TITLE
SQL connection fails (or something) after about unspecified amount of time

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#34]
The SQL connection fails (or something) after about 17 hours or someting like that, causing uploading to not work, you cannot log in and neither can /transparency be accessed as it reads from db

**Comment by Kattus** [comment]
It crashed again but now after just a few hours, running [PossibleCrashFix branch](/inabahare/lewd2/tree/PossibleCrashFix)

Output (spammed many times):
```
2019-01-04 02:11 +01:00: error: sorry, too many clients already
2019-01-04 02:11 +01:00:     at Connection.parseE (/var/www/lewd2/node_modules/pg/lib/connection.js:554:11)
2019-01-04 02:11 +01:00:     at Connection.parseMessage (/var/www/lewd2/node_modules/pg/lib/connection.js:379:19)
2019-01-04 02:11 +01:00:     at Socket.<anonymous> (/var/www/lewd2/node_modules/pg/lib/connection.js:119:22)
2019-01-04 02:11 +01:00:     at Socket.emit (events.js:182:13)
2019-01-04 02:11 +01:00:     at addChunk (_stream_readable.js:283:12)
2019-01-04 02:11 +01:00:     at readableAddChunk (_stream_readable.js:264:11)
2019-01-04 02:11 +01:00:     at Socket.Readable.push (_stream_readable.js:219:10)
2019-01-04 02:11 +01:00:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2019-01-04 02:11 +01:00: (node:8784) UnhandledPromiseRejectionWarning: error: sorry, too many clients already
2019-01-04 02:11 +01:00:     at Connection.parseE (/var/www/lewd2/node_modules/pg/lib/connection.js:554:11)
2019-01-04 02:11 +01:00:     at Connection.parseMessage (/var/www/lewd2/node_modules/pg/lib/connection.js:379:19)
2019-01-04 02:11 +01:00:     at Socket.<anonymous> (/var/www/lewd2/node_modules/pg/lib/connection.js:119:22)
2019-01-04 02:11 +01:00:     at Socket.emit (events.js:182:13)
2019-01-04 02:11 +01:00:     at addChunk (_stream_readable.js:283:12)
2019-01-04 02:11 +01:00:     at readableAddChunk (_stream_readable.js:264:11)
2019-01-04 02:11 +01:00:     at Socket.Readable.push (_stream_readable.js:219:10)
2019-01-04 02:11 +01:00:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2019-01-04 02:11 +01:00: (node:8784) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asy
nc function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-01-04 02:11 +01:00: (node:8784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are no
t handled will terminate the Node.js process with a non-zero exit code.
```
[full log of errors](https://gist.github.com/Kattus/a13df99d167a9dc0b16679613bf7a5a4)

**Comment by inabahare** [comment]
Will close tomorrow if there are no crashes overnight!

**Comment by inabahare** [comment]
I am considering this fixed!!!!!!!
