### ISSUE TITLE
Cannot reset passwords

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#42]
Trying to generate password reset link at /user/admin/reset-password results in
```
2019-01-13 21:36:19.1919+01:00: (node:17701) UnhandledPromiseRejectionWarning: error: column "token" of relation "UpdatePasswordKeys" does not exist
2019-01-13 21:36:19.1919+01:00:     at Connection.parseE (/var/www/lewd2/node_modules/pg/lib/connection.js:554:11)
2019-01-13 21:36:19.1919+01:00:     at Connection.parseMessage (/var/www/lewd2/node_modules/pg/lib/connection.js:379:19)
2019-01-13 21:36:19.1919+01:00:     at Socket.<anonymous> (/var/www/lewd2/node_modules/pg/lib/connection.js:119:22)
2019-01-13 21:36:19.1919+01:00:     at Socket.emit (events.js:182:13)
2019-01-13 21:36:19.1919+01:00:     at addChunk (_stream_readable.js:283:12)
2019-01-13 21:36:19.1919+01:00:     at readableAddChunk (_stream_readable.js:264:11)
2019-01-13 21:36:19.1919+01:00:     at Socket.Readable.push (_stream_readable.js:219:10)
2019-01-13 21:36:19.1919+01:00:     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2019-01-13 21:36:19.1919+01:00: (node:17701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2019-01-13 21:36:19.1919+01:00: (node:17701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by inabahare** [comment]
This is most likely done now as well
