### ISSUE TITLE
uploadUnit.value.toFixed is not a function

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#54]
```
2019-02-08 08:25:35.3535+01:00: Something went wrong on the info page TypeError: uploadUnit.value.toFixed is not a function
2019-02-08 08:25:35.3535+01:00:     at getStatistics (/var/www/lewd2/dist/app.js:365:40)
2019-02-08 08:25:35.3535+01:00:     at <anonymous>
2019-02-08 08:25:35.3535+01:00:     at process._tickCallback (internal/process/next_tick.js:188:7)
```
when accessing /info

**Comment by inabahare** [comment]
Boom
