### ISSUE TITLE
Impossible to register new accounts

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#77]
Steps to reproduce: 
1. Generate invite link
2. Try use the invitation
3. `Username already in use` no matter what username/password is entered.

No errors in log seem to be produced when I try this myself, but at the time of someone else trying, this could be observed in the log, related or not:
```
2020-02-27 16:15:32.3232+01:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2020-02-27 16:15:32.3232+01:00: TypeError: Cannot read property '0' of null
2020-02-27 16:15:32.3232+01:00:     at Strategy._passport.default.use._passportLocal.Strategy [as _verify] (/var/www/lewd2/dist/app.js:256:19)
2020-02-27 16:15:32.3232+01:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-02-27 16:15:32.3232+01:00: <app.js>
2020-02-27 16:15:32.3232+01:00: Reason:  TypeError: Cannot read property '0' of null
2020-02-27 16:15:32.3232+01:00:     at Strategy._passport.default.use._passportLocal.Strategy [as _verify] (/var/www/lewd2/dist/app.js:256:19)
2020-02-27 16:15:32.3232+01:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-02-27 16:15:32.3232+01:00: --------------------------
2020-02-27 16:15:32.3232+01:00: TypeError: Cannot read property '0' of null
2020-02-27 16:15:32.3232+01:00:     at Strategy._passport.default.use._passportLocal.Strategy [as _verify] (/var/www/lewd2/dist/app.js:256:19)
2020-02-27 16:15:32.3232+01:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-02-27 16:15:32.3232+01:00: --------------------------
2020-02-27 16:15:32.3232+01:00: Promise {
2020-02-27 16:15:32.3232+01:00:   <rejected> TypeError: Cannot read property '0' of null
2020-02-27 16:15:32.3232+01:00:       at Strategy._passport.default.use._passportLocal.Strategy [as _verify] (/var/www/lewd2/dist/app.js:256:19)
2020-02-27 16:15:32.3232+01:00:       at process._tickCallback (internal/process/next_tick.js:68:7) }
2020-02-27 16:15:32.3232+01:00: </app.js>
```

**Comment by inabahare** [comment]
Opa
