### ISSUE TITLE
unhandledRejection on invalid invitation token

### ISSUE THREAD

**Issue by Kattus** [inabahare/lewd2#80]
If trying to access an expired or invalid invitation link (such as https://lewd.se/register/asdf) the application crashes.
```
2020-04-11 21:53:22.2222+02:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2020-04-11 21:53:22.2222+02:00: TypeError: Cannot read property '0' of null
2020-04-11 21:53:22.2222+02:00:     at getTokenData (/var/www/lewd2/dist/app.js:1459:19)
2020-04-11 21:53:22.2222+02:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-04-11 21:53:22.2222+02:00: <app.js>
2020-04-11 21:53:22.2222+02:00: Reason:  TypeError: Cannot read property '0' of null
2020-04-11 21:53:22.2222+02:00:     at getTokenData (/var/www/lewd2/dist/app.js:1459:19)
2020-04-11 21:53:22.2222+02:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-04-11 21:53:22.2222+02:00: --------------------------
2020-04-11 21:53:22.2222+02:00: TypeError: Cannot read property '0' of null
2020-04-11 21:53:22.2222+02:00:     at getTokenData (/var/www/lewd2/dist/app.js:1459:19)
2020-04-11 21:53:22.2222+02:00:     at process._tickCallback (internal/process/next_tick.js:68:7)
2020-04-11 21:53:22.2222+02:00: --------------------------
2020-04-11 21:53:22.2222+02:00: Promise {
2020-04-11 21:53:22.2222+02:00:   <rejected> TypeError: Cannot read property '0' of null
2020-04-11 21:53:22.2222+02:00:       at getTokenData (/var/www/lewd2/dist/app.js:1459:19)
2020-04-11 21:53:22.2222+02:00:       at process._tickCallback (internal/process/next_tick.js:68:7) }
2020-04-11 21:53:22.2222+02:00: </app.js>
2020-04-11 21:53:23.2323+02:00: It's up and running in production mode :3
```

Running c5472271b891a4e96364c192800456e7256f578d

**Comment by inabahare** [comment]
I may have fixed this without knowing sometime in development. Locally I just get " The token wasn't found" as it should
